### ISSUE TITLE
Need a way to ignore view directories in more than extensions and app

### ISSUE THREAD

**Issue by daxpresents** [laMarciana/yiiDocumentor#2]
Doc generation is crashing when encountering view files in my /components/widgets/WIDGET_NAME/views folders

Not sure what the best fix for this one is.

Thanks for this great extension, I'm excited to work through these issues and get my app documented!! :)

**Comment by laMarciana** [comment]
Look at https://github.com/laMarciana/yiiDocumentor/issues/1#issuecomment-5856803

**Comment by daxpresents** [comment]
awesome, thanks for your help!
