### ISSUE TITLE
Can't find core class - CBaseUrlRule.php

### ISSUE THREAD

**Issue by daxpresents** [laMarciana/yiiDocumentor#3]
It's erroring when trying to document a component we made that extends CBaseUrlRule from the Yii core.

Building model...
PHP Error[2]: include(CBaseUrlRule.php): failed to open stream: No such file or directory
    in file /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/YiiBase.php at line 418
#0 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/YiiBase.php(418): autoload()
#1 unknown(0): autoload()
#2 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/components/HostedSiteUrlRule.php(11): spl_autoload_call()
#3 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/commands/doc/DocModel.php(65): require_once()
#4 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/commands/doc/DocModel.php(54): DocModel->findClasses()
#5 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/commands/DocCommand.php(419): DocModel->build()
#6 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/commands/DocCommand.php(282): DocCommand->buildModel()
#7 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/console/CConsoleCommandRunner.php(65): DocCommand->run()
#8 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/console/CConsoleApplication.php(91): CConsoleCommandRunner->run()
#9 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/base/CApplication.php(162): CConsoleApplication->processRequest()
#10 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/yii/framework/yiic.php(33): CConsoleApplication->run()
#11 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/yiic.php(7): require_once()
#12 /Users/dax/web_dev/htdocs/themml_yii_svn/trunk/www/themml/protected/yiic(4): require_once()

**Comment by laMarciana** [comment]
I think is the same problem that #1 and #2. It's a problem while including `HostedSiteUrlRule.php`, you need to exclude it:

https://github.com/laMarciana/yiiDocumentor/issues/1#issuecomment-5856803
