### ISSUE TITLE
yiiDocumentor does not recognize @todo tag

### ISSUE THREAD

**Issue by wildanm** [laMarciana/yiiDocumentor#4]
When generating the doc, it seems that yiiDocumentor does not recognize @todo tag, it's an intended behaviour or i miss something here ?

**Comment by SebSept** [comment]
I don't think that's a bug, just an intended behavior. but could be a good feature ...

**Comment by waiting-for-dev** [comment]
yiiDocumentor just extends the functionality of Yii native framework api generator, so if it is not supported there, it is not supported here. Thanks.
