### ISSUE TITLE
Please provide an output screenshot or demo page.

### ISSUE THREAD

**Issue by NabiKAZ** [laMarciana/yiiDocumentor#6]
Please provide an output screenshot or demo page.

**Comment by waiting-for-dev** [comment]
Hey @NabiKAZ . I'm sorry to say that this extension is currently unmaintained. I developed it in 2012, and I would be surprised if it works in recent Yii versions (I haven't tried, so I don't know. I'm not a Yii user anymore). But, about the output, it creates html pages in the `<output-path>` you provide.

Cheers

**Comment by NabiKAZ** [comment]
Thanks I try it and take a screenshot for anyone.

![screenshot-yiidoc](https://cloud.githubusercontent.com/assets/246721/25037659/9bcd31ba-210f-11e7-960c-617bd65e96a2.png)
